Vagrant.configure(2) do |config|

  config.vm.define "linux-vm", autostart: true do |config|
    config.vm.box = "ubuntu/trusty64"
    config.vm.hostname = "linux-vm"
    config.vm.network :forwarded_port, guest: 22, host: 3222, id: 'ssh'
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
  end

end