Vagrant.configure(2) do |config|

  config.vm.define "gns3-vm", autostart: false do |config|
    config.vm.box = "file://./packer_virtualbox-ovf_virtualbox.box"
    config.vm.network "public_network"
    config.ssh.username = "gns3"
    config.ssh.password = "gns3"
    config.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.memory = "4096"
    end
    config.vm.network "forwarded_port", guest: 8000, host: 8000
  end

  config.vm.define "juniper-vsrx", autostart: false do |config|
    config.vm.box = "juniper/ffp-12.1X47-D15.4-packetmode"
    config.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.memory = "4096"
    end
    config.vm.network "private_network",
                      ip: "192.168.33.10",
                      virtualbox__intnet: "teststatic",
                      auto_config: false
    config.ssh.insert_key = false
    config.vm.synced_folder '.', '/vagrant', disabled: true
  end

  config.vm.define "arista-vm", autostart: false do |config|
    config.vm.box = "file://./arista-vm.box"
    config.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.memory = "4096"
    end
    config.ssh.username = "admin"
    config.ssh.password = "admin"
    config.vm.synced_folder '.', '/vagrant', disabled: true
  end
end